### ISSUE TITLE
Custom `mkremote` headers are overridden

### ISSUE THREAD

**Issue by syk0saje** [hoplon/castra#20]
As can be seen here (https://github.com/hoplon/castra/blob/master/src/castra/core.cljs#L91):

``` clj
(merge opts {:headers headers :body body})
```

should probably be something like this:

``` clj
(assoc opts
  :headers (merge (:headers opts) headers)
  :body body)
```

**Comment by syk0saje** [comment]
Project no longer maintained, closing.

**Comment by alandipert** [comment]
This project is maintained. A PR for this issue would be considered.
